'use client'
import Providers from "@/redux/Providers";
import { Inter } from "next/font/google";
import { useState } from "react";
import { Cart, Footer, Navbar } from "./components";
import "./globals.scss";


const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [openCart, setOpenCart] = useState(false)
  

  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
      <link href="https://fonts.googleapis.com/css2?family=Londrina+Shadow&family=Monoton&display=swap" rel="stylesheet"/>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js"
   integrity="sha512-MY2jfK3DBnVzdS2V8MXo5lRtr0mNRroUI9hoLVv2/yL3vrJTam3VzASuKQ96fLEpyYIT4a8o7YgtUs5lPjiLVQ=="
   crossorigin="anonymous"
   referrerpolicy="no-referrer"></script> 
      </head>
      <body className={inter.className} style={{overflowX:"hidden"}}>
        <Providers>
          <Navbar
            setOpenCart={setOpenCart}
          />
          <Cart
            openCart={openCart}
            setOpenCart={setOpenCart}
          />
          {children}
          <Footer />
        </Providers>
        </body>
    </html>
  );
}
